"""Crear tabla articulos

Revision ID: 7d034ae8ad89
Revises: d4867f3a4c0a
Create Date: 2020-10-24 17:01:57.165021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d034ae8ad89'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articulo_id', table_name='articulo')
    op.drop_index('ix_articulo_url', table_name='articulo')
    op.drop_table('articulo')
    op.add_column('article', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de última actualización'))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('article', 'last_updated')
    op.create_table('articulo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('origen', sa.VARCHAR(), autoincrement=False, nullable=False, comment='De qué web viene el artículo'),
    sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Título para mostrar en la lista'),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Link'),
    sa.Column('favorito', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='True si está añadido a favoritos'),
    sa.Column('resumen', sa.TEXT(), autoincrement=False, nullable=False, comment='Se puede poner el principio del texto aquí, por si no se quiere abrir la url'),
    sa.PrimaryKeyConstraint('id', name='articulo_pkey')
    )
    op.create_index('ix_articulo_url', 'articulo', ['url'], unique=True)
    op.create_index('ix_articulo_id', 'articulo', ['id'], unique=False)
    # ### end Alembic commands ###
