"""Crear tabla search terms

Revision ID: e57480c224d9
Revises: 7d034ae8ad89
Create Date: 2020-10-25 17:15:01.865103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57480c224d9'
down_revision = '7d034ae8ad89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchterm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(), nullable=False, comment='Término de búsqueda para filtros'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searchterm_id'), 'searchterm', ['id'], unique=False)
    op.create_index(op.f('ix_searchterm_term'), 'searchterm', ['term'], unique=True)
    op.alter_column('article', 'summary',
               existing_type=sa.TEXT(),
               comment='Se puede poner un resumen del texto aquí, por si no se quiere abrir la url',
               existing_comment='Se puede poner el principio del texto aquí, por si no se quiere abrir la url',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'summary',
               existing_type=sa.TEXT(),
               comment='Se puede poner el principio del texto aquí, por si no se quiere abrir la url',
               existing_comment='Se puede poner un resumen del texto aquí, por si no se quiere abrir la url',
               existing_nullable=False)
    op.drop_index(op.f('ix_searchterm_term'), table_name='searchterm')
    op.drop_index(op.f('ix_searchterm_id'), table_name='searchterm')
    op.drop_table('searchterm')
    # ### end Alembic commands ###
